### PR TITLE
Return early if error is encountered while fetching vsp ticket info

### LINKED ISSUE #102: [Staking]: clicking on a staking transaction crashes the app
Screenshot from 2023-09-26 11-17-36

i clicked on the voted transaction and the app crashed, subsequently clicking on revoked and other staking transactions crashes the app

```
2023-09-26 11:15:01.807 [WRN] DCR: unable to getWallet info using ticket: 7bfdd587a9020734686ed3c40b19f7f7a96a20b8794565ea2d9fa014946cdff0 Error: item does not exist: no VSP info for ticket 7bfdd587a9020734686ed3c40b19f7f7a96a20b8794565ea2d9fa014946cdff0
2023-09-26 11:15:01.807 [ERR] UI: VSPTicketInfo error: item does not exist: no VSP info for ticket 7bfdd587a9020734686ed3c40b19f7f7a96a20b8794565ea2d9fa014946cdff0
2023-09-26 11:15:01.807 [WRN] DCR: unable to getWallet info using ticket: 7bfdd587a9020734686ed3c40b19f7f7a96a20b8794565ea2d9fa014946cdff0 Error: item does not exist: no VSP info for ticket 7bfdd587a9020734686ed3c40b19f7f7a96a20b8794565ea2d9fa014946cdff0
2023-09-26 11:15:01.807 [ERR] UI: VSPTicketInfo error: item does not exist: no VSP info for ticket 7bfdd587a9020734686ed3c40b19f7f7a96a20b8794565ea2d9fa014946cdff0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12e7c08]

goroutine 1228 [running]:
github.com/crypto-power/cryptopower/ui/page/transaction.(*TxDetailsPage).OnNavigatedTo.func1()
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/transaction/transaction_details_page.go:228 +0x2a8
created by github.com/crypto-power/cryptopower/ui/page/transaction.(*TxDetailsPage).OnNavigatedTo
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/transaction/transaction_details_page.go:216 +0x1ea
exit status 2
```

### PR DESCRIPTION
**Pull request by ukane-philemon**
Closes #102

### CODE REVIEW

**Comment by dreacot** [comment]
Looks good!

do you want to look into why getting the vsp fee and info fails in this PR or do you want to create a follow up issue?

**Comment by ukane-philemon** [comment]
> follow up issue?

I think follow up is better.

**Review by dreacot — APPROVED** [review]

**Comment by dreacot** [comment]
okay, please create one

**Comment by ukane-philemon** [comment]
> do you want to look into why getting the vsp fee and info fails

@dreacot I think we don't have issues with this^. Maybe it was the user's network connection.

Screenshot 2023-10-01 at 12 18 52 AM

**Comment by dreacot** [comment]
yes, getting those info before staking works, but after staking i can't view vsp or ticket fee. not network related for me

i've created an issue https://github.com/crypto-power/cryptopower/issues/138

**Pull request merged**
