### PR TITLE
ui, wallet, version: house cleaning

### PR DESCRIPTION
**Pull request by ukane-philemon**
- Fix comment formatting
- Fix typos
- Fix variable and func naming

A good tool I use is the vscode [Rewrap extension](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap), which keeps comments well-formatted and consistent.

### CODE REVIEW

**Review by Sirmorrison — COMMENTED** [review]
111 files changed. Thats too much for a single PR. I see the description is talking about doing 3 or more stuff in this PR. My recommendation will be a break them down.

I recommend keeping your PRs really small.. If possible under 20 file changes. It helps for faster and easier code reviews.

**Comment by ukane-philemon** [comment]
> 111 files changed. Thats too much for a single PR. I see the description is talking about doing 3 or more stuff in this PR. My recommendation will be a break them down.

I agree 111 is massive but 98% of it are non-code changes, mostly formatting and typo fixes all in the same scope. Maybe I wrongly assumed this would cause less review stress than code review.

**Comment by dreacot** [comment]
it's a lot of changes, even though i see most of it is just formatting, devs still need to go through each changed file. seems like it would cause review strain right now. i can imagine merging this now could cause a lot of conflicts for devs, possibly.

i appreciate the clean up work, good initiative

this might just take longer to review/merge, due to higher priority reviews

**Comment by ukane-philemon** [comment]
I’ll begin to break this cleanup into small chunks in the coming days.

**Comment by ukane-philemon** [comment]
Too gigantic and I'm beginning to lose track of those I've fixed in other PR. I'll proly come back to pick a few things but I'm closing this now.

**Pull request closed without merging**
