### PR TITLE
Prevent duplicate notification registration

### LINKED ISSUE #109: UI: Error adding tx and block notification listener: listener_already_exist
Error observed when using the app for the first time.
```
[ERR] UI: Error adding tx and block notification listener: listener_already_exist
```
Sorry I don't have any other context at this time not sure exactly when it happened.

### PR DESCRIPTION
**Pull request by ukane-philemon**
closes #109.

To reproduce the issue: Navigate between the wallet_select page and the wallet main page in quick succession twice.

### CODE REVIEW

**Comment by ukane-philemon** [comment]
A wild goroutine is responsible for cleaning up and deregistering the listeners but might not have concluded before the request to register again.

I’ll revisit to reduce code changes.

**Comment by ukane-philemon** [comment]
@dreacot I’m thinking about listeners having their separate I’d. This is because a wild goroutine can potentially deregister a listener for a displayed page with our current pattern.

Page adds listener > Quickly switching to and fro would cause same listener to be re-registered before the cleanup select case executes. We get an error about multiple listener registrations and then the wild goroutine eventually fires and clears up the first listener since they share a command unique id. Then we have no listener at all for the page.

**Comment by dreacot** [comment]
> @dreacot I’m thinking about listeners having their separate I’d. This is because a wild goroutine can potentially deregister a listener for a displayed page with our current pattern.
> 
> Or do the cleanup when we cancel the page context.
> 
> Problem: Page adds listener > Quickly switching to and fro would cause same listener to be re-registered before the cleanup select case executes. We get an error about multiple listener registrations and then the wild goroutine eventually fires and clears up the first listener since they share a common unique id. Then we have no listener at all for the page.

go for it

**Comment by ukane-philemon** [comment]
Replaced by #195

**Pull request closed without merging**
