### PR TITLE
Removed wallet backup button and make the backup warning clickable

### LINKED ISSUE #598: "wallet backup needed" should be clickable with maybe a red background while "backup now" can be removed

### PR DESCRIPTION
**Pull request by ademuanthony**
Close #598 
image

### CODE REVIEW

**Comment by dreacot** [comment]
@ademuanthony use a red background not red text colour

**Comment by ademuanthony** [comment]
> @ademuanthony use a red background not red text colour

image

**Comment by ademuanthony** [comment]
> > @ademuanthony use a red background not red text colour
> 
> image

image

**Comment by ademuanthony** [comment]
image

**Review by dreacot — APPROVED** [review]

**Pull request merged**
