### PR TITLE
refactor dropdown layout

### PR DESCRIPTION
**Pull request by bugjt**
This PR following changes:
- Refactor dropdown layout
- The dropdown icon in the wallet details page appears to be text so far

image
image

### CODE REVIEW

**Comment by JustinBeBoy** [comment]
The width of the dropdown should be equal to the width of the displayed options. I don't think we need to increase width?

image

**Comment by dreacot** [comment]
> The width of the dropdown should be equal to the width of the displayed options

i think you have a point probably should use width of the largest item? but what happens when the largest item is too long, obviously to truncate right?, so what's too long in this case?

**Comment by JustinBeBoy** [comment]
> > The width of the dropdown should be equal to the width of the displayed options
> 
> i think you have a point probably should use width of the largest item? but what happens when the largest item is too long, obviously to truncate right?, so what's too long in this case?

the width of dropdown have define max width, so we don't need do it, if dropdown and dropdown menu have different width so ui not good for me

**Comment by dreacot** [comment]
@bugjt justindo has a good point

let's just use a sane max width and truncate anything longer than that

**Comment by bugjt** [comment]
This means we will have the dropdown and the dropdown menu the same size and both will be the width of the largest item. Is that correct?

**Comment by bugjt** [comment]
We cannot rename names longer than 20 characters and when the name is too long it will be truncated with "..."

image
image

**Comment by dreacot** [comment]
so the truncation is where i was getting to, the screenshot by the left works well. seem it truncates after 10 characters

**Comment by bugjt** [comment]
So we will cut after 10 characters or 20 characters (default maxDropdownItemTextLen = 20)?

**Comment by bugjt** [comment]
If the width of the dropdown is equal to the length of the largest element, it will look like this:
image

**Comment by dreacot** [comment]
image

This is okay

**Comment by bugjt** [comment]
It's ready for review.
image

**Review by JustinBeBoy — CHANGES_REQUESTED** [review]
How can I scroll to see the last wallet?

image

**Comment by dreacot** [comment]
i want to move the dropdown and balance to the same line on mobile.

For the sake of the mobile implementation, i'' say we revert the dropdown to a dynamic width

**Comment by bugjt** [comment]
> i want to move the dropdown and balance to the same line on mobile.
> 
> For the sake of the mobile implementation, i'' say we revert the dropdown to a dynamic width 

I think we should hide "watch only" label on watch only wallet

**Comment by dreacot** [comment]
> I think we should hide "Watch-Only" label on watch only wallet

I agree

**Comment by bugjt** [comment]
It's ready for review.

**Review by dreacot — APPROVED** [review]

**Pull request merged**
