### PR TITLE
Fix overlapped top navigation bar

### PR DESCRIPTION
**Pull request by dmigwi**
Closes https://github.com/crypto-power/cryptopower/issues/38
Before: 

image

After:

image

### CODE REVIEW

**Comment by dreacot** [comment]
in your after screenshot, i can see a little space after the top bar, the top starting point should be right immediately after the app window.

for me, however the gap is much wider

Screenshot 2023-08-21 at 5 12 27 PM

**Comment by dmigwi** [comment]
How does it look on your end on master? Can you see that the top bar
overlap?

**Comment by dreacot** [comment]
Screenshot 2023-08-21 at 7 02 39 PM

**Comment by dmigwi** [comment]
Maybe its only on my machine that its acting up. I remember crux reported this a while back. we can hold on this until we identify why its works on your end but fails on mine.

I hope go 1.21 version update has no relation with this UI overlap

**Comment by dreacot** [comment]
> I hope go 1.21 version update has no relation with this UI overlap

i just updated to 1.21, still shows fine for me

**Comment by dmigwi** [comment]
Then this must be something unique to my system. I  will dig more to
understand the course

**Comment by Sirmorrison** [comment]
The PR has deprecated UI and currently stalled. Closing as Staled.

**Pull request closed without merging**
