### PR TITLE
Read request body only once

### PR DESCRIPTION
**Pull request by dmigwi**
Closes https://github.com/crypto-power/cryptopower/issues/43

`KeepReqAlive` params indicates that the upstream caller wants to manage the request closure.

### CODE REVIEW

**Comment by dreacot** [comment]
i get this error, still on testnet

```
2023-08-16 08:43:36.815 [INF] DCR: [1] Running ticket buyer
2023-08-16 08:44:20.239 [ERR] DCR: [1] Ticket purchasing failed: cannot authenticate server: invalid signature
```

mainnet doesn't throw any errors, but doesn't purchase any tickets even after an hour

**Comment by dmigwi** [comment]
Issue resolved:

```
2023-08-16 12:42:42.888 [INF] DCR: The wallet has been unlocked without a time limit
2023-08-16 12:42:43.106 [INF] DCR: [10] Running ticket buyer
2023-08-16 12:43:00.996 [INF] DCR: Reserved credits for 1 tickets: total fee: 0.00036284 DCR
2023-08-16 12:43:00.996 [INF] DCR: Returning address (account=0 branch=1 child=33)
2023-08-16 12:43:00.996 [INF] DCR: selected input 82b37883afe5392ecfeba009ae2c6240ac9f3909de1dc9aa5aa942fe022104c4:1 (0.00262144 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 29d8df43f5b868692e9b840fe87c7d0c996064ccc853547b1fdee03ca8efe7ef:6 (2.68435456 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input b4ae45f3126430848d9f34fb0144b7bda39101f0cf0ffbef2df459c9814dae53:5 (0.16777216 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 82b37883afe5392ecfeba009ae2c6240ac9f3909de1dc9aa5aa942fe022104c4:0 (0.00262144 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 38b5a236d185b9d39968fa20215c945e0771e99babc92b2cb5d955c80f55bc59:7 (0.04194304 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 39a6f02b9c4fcb2d5d0b075364c2fcc9d17202d83279ba48c9335a3507e1a016:11 (10.73741824 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input f3193dcf24c73078f99b10af4f87e7c99240c14e29abd40112feb8ee16a452d5:1 (2.68365029 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 38b5a236d185b9d39968fa20215c945e0771e99babc92b2cb5d955c80f55bc59:2 (0.04194304 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 3208fdcfb4d05e08f730d054065f20e2b8033cad0e2f7959fb26dc209a01d0ce:0 (0.67108864 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 38b5a236d185b9d39968fa20215c945e0771e99babc92b2cb5d955c80f55bc59:6 (0.04194304 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 29d8df43f5b868692e9b840fe87c7d0c996064ccc853547b1fdee03ca8efe7ef:13 (2.68435456 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 3208fdcfb4d05e08f730d054065f20e2b8033cad0e2f7959fb26dc209a01d0ce:4 (0.67108864 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 39a6f02b9c4fcb2d5d0b075364c2fcc9d17202d83279ba48c9335a3507e1a016:1 (10.73741824 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 019138750e6ae185e29306388f0603422005a7d4990a2d8ca2ace174b8727b0f:3 (0.16777216 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input d60bd8bb76f197e3eaba8369f47bf7d708afcc9d284051b15e0990ab993f8bf9:5 (0.04194304 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 4d314665df6f325124d2c148a16b2120c6e6da77f4d3c02756c58211051ff804:15 (2.68435456 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 39a6f02b9c4fcb2d5d0b075364c2fcc9d17202d83279ba48c9335a3507e1a016:10 (10.73741824 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 29d8df43f5b868692e9b840fe87c7d0c996064ccc853547b1fdee03ca8efe7ef:2 (2.68435456 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 4d314665df6f325124d2c148a16b2120c6e6da77f4d3c02756c58211051ff804:18 (2.68435456 DCR) for ticket purchase split transaction
2023-08-16 12:43:00.996 [INF] DCR: selected input 4d314665df6f325124d2c148a16b2120c6e6da77f4d3c02756c58211051ff804:2 (2.68435456 DCR) for ticket purchase split transaction
2023-08-16 12:43:02.147 [INF] DCR: Dialed CSPPServer 192.168.8.105:48824 -> 149.28.110.221:15760
2023-08-16 12:43:10.775 [INF] DCR: Returning address (account=1 branch=0 child=102)
2023-08-16 12:43:16.376 [INF] DCR: Completed CoinShuffle++ mix of ticket split transaction 481ee0362327fc46b4539ddf1369a6c1d264be7b16b0daea4fd2a1893c42357a
2023-08-16 12:43:16.377 [INF] WLLT: Inserting unconfirmed transaction 481ee0362327fc46b4539ddf1369a6c1d264be7b16b0daea4fd2a1893c42357a
2023-08-16 12:43:16.379 [INF] DCR: Split output is 481ee0362327fc46b4539ddf1369a6c1d264be7b16b0daea4fd2a1893c42357a:11
2023-08-16 12:43:16.380 [INF] DCR: [10] New Transaction 481ee0362327fc46b4539ddf1369a6c1d264be7b16b0daea4fd2a1893c42357a
2023-08-16 12:43:16.380 [INF] DCR: Returning address (account=0 branch=1 child=34)
2023-08-16 12:43:16.381 [INF] DCR: Returning address (account=1 branch=0 child=103)
2023-08-16 12:43:16.382 [INF] WLLT: Inserting unconfirmed transaction 077fd5f1454738085521a61dd67fc429a8110ef2f24d0ba6ea036ebca956e210
2023-08-16 12:43:16.385 [INF] DCR: [10] New Transaction 077fd5f1454738085521a61dd67fc429a8110ef2f24d0ba6ea036ebca956e210
```

**Comment by dreacot** [comment]
2023-08-16 10:56:25.823 [INF] DCR: [1] Running ticket buyer
2023-08-16 10:59:27.911 [INF] DCR: Returning address (account=0 branch=1 child=0)
2023-08-16 10:59:27.916 [INF] DCR: Returning address (account=0 branch=1 child=1)
2023-08-16 10:59:27.921 [INF] WLLT: Inserting unconfirmed transaction ab9fe2ff25ebf827ec125bf10ea4cee10fc3d381db28a22ea95fd080cc6d79d6
2023-08-16 10:59:27.947 [INF] DCR: [1] New Transaction ab9fe2ff25ebf827ec125bf10ea4cee10fc3d381db28a22ea95fd080cc6d79d6
2023-08-16 10:59:28.081 [INF] DCR: Reserved credits for 1 tickets: total fee: 0.00008345 DCR
2023-08-16 10:59:28.082 [INF] DCR: Returning address (account=2 branch=1 child=0)
2023-08-16 10:59:28.082 [INF] DCR: selected input ab9fe2ff25ebf827ec125bf10ea4cee10fc3d381db28a22ea95fd080cc6d79d6:0 (119.99982905 DCR) for ticket purchase split transaction
2023-08-16 10:59:29.725 [INF] DCR: Dialed CSPPServer 192.168.0.189:64063 -> 149.28.110.221:15760
2023-08-16 11:03:30.122 [INF] DCR: Returning address (account=1 branch=0 child=0)
2023-08-16 11:03:36.274 [INF] DCR: Completed CoinShuffle++ mix of ticket split transaction fd6e66cd1a57a878676041173c97183916c512930b4a25aa04f500e8cfff034b
2023-08-16 11:03:36.297 [INF] WLLT: Inserting unconfirmed transaction fd6e66cd1a57a878676041173c97183916c512930b4a25aa04f500e8cfff034b
2023-08-16 11:03:36.314 [INF] DCR: Split output is fd6e66cd1a57a878676041173c97183916c512930b4a25aa04f500e8cfff034b:5
2023-08-16 11:03:36.324 [INF] DCR: Returning address (account=0 branch=1 child=2)
2023-08-16 11:03:36.335 [INF] DCR: [1] New Transaction fd6e66cd1a57a878676041173c97183916c512930b4a25aa04f500e8cfff034b
2023-08-16 11:03:36.339 [INF] DCR: Returning address (account=1 branch=0 child=1)
2023-08-16 11:03:36.343 [INF] WLLT: Inserting unconfirmed transaction fdf55cd9013dc27a0f28538e15585355301ef16cfc511db6cdf3616f801d5aa7
2023-08-16 11:03:36.375 [INF] DCR: [1] New Transaction fdf55cd9013dc27a0f28538e15585355301ef16cfc511db6cdf3616f801d5aa7
2023-08-16 11:04:21.205 [INF] DCR: Published ticket purchase fdf55cd9013dc27a0f28538e15585355301ef16cfc511db6cdf3616f801d5aa7
2023-08-16 11:04:21.806 [INF] DCR: [1] Purchased ticket fdf55cd9013dc27a0f28538e15585355301ef16cfc511db6cdf3616f801d5aa7 at stake difficulty 52.77976671 DCR
2023-08-16 11:04:32.237 [ERR] VSPC: ticket fdf55cd9013dc27a0f28538e15585355301ef16cfc511db6cdf3616f801d5aa7: reconcile payment: error: status: 400 Bad Request resp: {"code":0,"message":"no VSP-Client-Signature header"}

ticket purchased successfully, peep the last error log though, not sure what that's about

**Comment by dreacot** [comment]
also opening the ticket shows this

```
2023-08-16 11:14:33.776 [ERR] UI: [WARN] Ticket fdf55cd9013dc27a0f28538e15585355301ef16cfc511db6cdf3616f801d5aa7 is not confirmed by VSP https://testnet-vsp.jholdstock.uk. Fee tx 0000000000000000000000000000000000000000000000000000000000000000, status "fee payment errored" 
```

most likely why the fee isn't available, please let me know if you'd like this as a new issue @dmigwi 

Screenshot 2023-08-16 at 11 23 23 AM

**Comment by dreacot** [comment]
i get this when viewing a ticket

```
2023-08-16 14:50:35.627 [WRN] DCR: unable to get vsp ticket: 5cdf8cb5807c7f82d2cc**** Error: cannot authenticate server: invalid signature
```

**Pull request merged**
