### PR TITLE
Refactor wallet info page and reduce text size in shared componenets for mobile

### LINKED ISSUE #270: [Mobile]: implement wallet info page
use figma!

Image

NB: recent tx doesn't currently show for btc and ltc

### PR DESCRIPTION
**Pull request by ukane-philemon**
- Fix some bugs on the wallet info page
- Refactor the wallet info page and reduce text size (in shared components used by the wallet info page)  for mobile
Closes #270 

Note to reviewers: I currently do not have staking, btc and ltc txs to test with atm. This means the second part of #270 is yet to be verified/fixed but I'm putting this up for review and comments—also, a minor tweak of the mobile wallet info card to improve mobile display is part of this PR. 
 
This PR:
Screenshot 2023-12-15 at 2 45 21 AM

Figma: 
Screenshot 2023-12-15 at 2 51 56 AM

### CODE REVIEW

**Comment by dreacot** [comment]
staking needs some work

Screenshot from 2023-12-14 19-16-46

tx still not showing for btc and ltc

Screenshot from 2023-12-14 19-17-34

**Comment by ukane-philemon** [comment]
Screenshot 2023-12-15 at 6 26 38 PM

**Comment by ukane-philemon** [comment]
This PR is directly affected by #335 and since it's more focused, I think this PR would have to wait for that change. Any thoughts?

**Comment by dreacot** [comment]
@ukane-philemon the tx items and staking items are not clickable

**Review by dreacot — APPROVED** [review]

**Pull request merged**
