### PR TITLE
add bottom nav to replace homepage tabs on mobile

### LINKED ISSUE #124: [Mobile]: add bottom nav
use figma!

Image

### PR DESCRIPTION
**Pull request by dreacot**
closes #124 

This PR adds the following;
- the bottom nav for the home page
- the send and receive button for mobile

### CODE REVIEW

**Comment by JoeGruffins** [comment]
On a newer android I see the Governance tab but clicking does nothing. Is this intended?

**Comment by JoeGruffins** [comment]
Adding a second wallet got a little weird:
Screenshot_20231006_112707

**Comment by dreacot** [comment]
> On a newer android I see the Governance tab but clicking does nothing. Is this intended?
> 
> I see no Governance tab on desktop.

yes, this is correct, there's an issue to bring governance to the homepage https://github.com/crypto-power/cryptopower/issues/130

until that is merged the bottom nav menu entry for governance won't work

**Comment by dreacot** [comment]
> Adding a second wallet got a little weird:
> 
> double navigator
> Screenshot_20231006_112707

yes, this is from master, would need to be resolved as part of  https://github.com/crypto-power/cryptopower/issues/145

**Review by JoeGruffins — APPROVED** [review]
I'm unable to comment on the gogio specific bits yet but looks ok to me, besides the preexisting double bar.

**Pull request merged**
