### PR TITLE
Update layout Send page and send modal for mobile version

### LINKED ISSUE #216: update send modal layout

### LINKED ISSUE #289: [Mobile]: layout send page
use fimga!

### LINKED ISSUE #291: [Mobile]: layout send modal
use figma!

### LINKED ISSUE #344: [Mobile]; fix coin control page layout
adjust the coin control page layout to look better on mobile

### PR DESCRIPTION
**Pull request by JustinBeBoy**
Resolves #289 
Resolves #291 
Resolves #344 
Resolves #216 

**Screenshot**

image

image

### CODE REVIEW

**Comment by dreacot** [comment]
the send modal does not contain coin control, it also doesn't contain fee rate for btc and ltc


Screenshot from 2023-12-20 09-38-39

**Comment by dreacot** [comment]
the entire coin selection row should be clickable
Screenshot from 2023-12-20 09-45-55

**Comment by dreacot** [comment]
on the send modal, the margin between advanced options and description note is too long.

clicking on coin selection opens the coin selection page behind the modal, it should probably open up inside another modal

Screenshot from 2023-12-21 11-43-14

**Comment by JustinBeBoy** [comment]
> on the send modal, the margin between advanced options and description note is too long.
> 
> clicking on coin selection opens the coin selection page behind the modal, it should probably open up inside another modal
> 
> Screenshot from 2023-12-21 11-43-14
> 
> fee rate dropdown does not show for ltc on the send modal and on the send page
> 
> Screenshot from 2023-12-21 11-46-43
> 
> on mobile each amount field can take full width (look at centralized exchange page on mobile) Screenshot from 2023-12-21 11-48-56

I need to research old logic,because the current logic is very different from what you asked for

**Comment by dreacot** [comment]
> > on the send modal, the margin between advanced options and description note is too long.
> > clicking on coin selection opens the coin selection page behind the modal, it should probably open up inside another modal
> > Screenshot from 2023-12-21 11-43-14
> > fee rate dropdown does not show for ltc on the send modal and on the send page
> > Screenshot from 2023-12-21 11-46-43
> > on mobile each amount field can take full width (look at centralized exchange page on mobile) Screenshot from 2023-12-21 11-48-56
> 
> I need to research old logic,because the current logic is very different from what you asked for

can you elaborate? what part is going to be a problem?

**Comment by dreacot** [comment]
the back button on the send modal doesn't work

Screenshot from 2023-12-27 11-19-46

**Comment by dreacot** [comment]
> fee rate dropdown does not show for ltc on the send modal and on the send page

this hasn't been fixed

**Review by dreacot — APPROVED** [review]

**Pull request merged**
