### PR TITLE
layout overview page for mobile

### LINKED ISSUE #125: [Mobile]: implement the overview page design
use figma!
Overview page Decred

### PR DESCRIPTION
**Pull request by dreacot**
closes #125 

This MR lays out the overview page for mobile, it does not include api/live data implementations, those would be broken down into different PRs. also the desktop is yet to implement live data for some cards, once those are done there would be follow up issues to populate the cards respective cards. The aim of this PR is simply to provide overview layout for the mobile apps

### CODE REVIEW

**Comment by dreacot** [comment]
@Sirmorrison pointed out an issues with the asset balance slider https://github.com/crypto-power/cryptopower/pull/118#issuecomment-1740561191 that causes the radius to look weird

**Comment by JoeGruffins** [comment]
> @Sirmorrison pointed out an issues with the asset balance slider https://github.com/crypto-power/cryptopower/pull/118#issuecomment-1740561191 that causes the radius to look weird

Also cannot flick the slider to see other coins.

**Comment by dreacot** [comment]
> > @Sirmorrison pointed out an issues with the asset balance slider [#118 (comment)](https://github.com/crypto-power/cryptopower/pull/118#issuecomment-1740561191) that causes the radius to look weird
> 
> Also cannot flick the slider to see other coins.

Actually the slider shows the total balance for all asset type, e.g (if you have 3 dcr wallets, it sums up the balance and displays on the dcr asset slider, if you have no other btc/ltc, you won't see the sliders for btc/ltc).

But if you're referring to a fluid transition between sliders, when you flick them, then yes, that would make a lot of sense and would be desirable. We opted not to implement that initially for simplicity.

But I'd create an issue so the sliders can be enhanced

**Comment by dreacot** [comment]
> @Sirmorrison pointed out an issue with the asset balance slider [#118 (comment)](https://github.com/crypto-power/cryptopower/pull/118#issuecomment-1740561191) that causes the radius to look weird

this is the issue in question https://github.com/crypto-power/cryptopower/issues/140

**Pull request merged**
