### PR TITLE
staking: Fix nil dropdown panic.

### LINKED ISSUE #318: clicking on staking activity while in a wallet causes the app to crash
go to the wallets page, open a dcr wallet, click the transactions menu, and then click on staking activity the app crashes

Image

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1317444]

goroutine 54 [running]:
github.com/crypto-power/cryptopower/ui/cryptomaterial.(*DropDown).SelectedIndex(...)
        /home/user/Projects/src/github.com/dreacot/cryptopower/ui/cryptomaterial/dropdown.go:149
github.com/crypto-power/cryptopower/ui/page/transaction.(*TransactionsPage).HandleUserInteractions(0xc004dede00)
        /home/user/Projects/src/github.com/dreacot/cryptopower/ui/page/transaction/transactions_page.go:518 +0x3c4
github.com/crypto-power/cryptopower/ui/page/root.(*SingleWalletMasterPage).HandleUserInteractions(0xc003f38100)
        /home/user/Projects/src/github.com/dreacot/cryptopower/ui/page/root/main_page.go:267 +0x67
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).HandleUserInteractions(0xc003f36d00)
        /home/user/Projects/src/github.com/dreacot/cryptopower/ui/page/root/home_page.go:180 +0x67
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc0039323f0, {{0xc1565fbcf00f7ad0, 0x152e18c2c0, 0x2e658a0}, {0x3f800000, 0x3f800000}, {0x780, 0x417}, {0x0, 0x0, ...}, ...})
        /home/user/Projects/src/github.com/dreacot/cryptopower/ui/window.go:224 +0x197
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc0039323f0)
        /home/user/Projects/src/github.com/dreacot/cryptopower/ui/window.go:195 +0x2b9
main.main.func3()
        /home/user/Projects/src/github.com/dreacot/cryptopower/main.go:109 +0x1d
created by main.main
        /home/user/Projects/src/github.com/dreacot/cryptopower/main.go:107 +0x51d
exit status 2
```

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #318 

This fixes the panic, but unsure if the transactions look right as I have no staking transactions yet as the testnet mixer has been down forever.

### CODE REVIEW

**Comment by dreacot** [comment]
seems similar fixed has been done here https://github.com/crypto-power/cryptopower/pull/327/files#diff-e72b3c2bc9a1b4867a4c20405cdfa716d6e1c88a20bf2b2fac92809da4555e52R568

bu i'd merge this as #327 could take longer to get in

**Review by dreacot — CHANGES_REQUESTED** [review]
[Screencast from 2023-12-14 11.03.04.webm](https://github.com/crypto-power/cryptopower/assets/25265396/15b2622d-e084-493f-ae04-45d6d88a2bb9)

i'm unable to see the staking transactions

**Comment by JoeGruffins** [comment]
> i'm unable to see the staking transactions

Sorry was afraid of that. I need some staking transactions to test. I guess I can restore a different wallet with decrediton seed?

**Comment by JoeGruffins** [comment]
hmm, I restored a wallet with 47k txn and it has a lot of stake transactions. The transactions page takes forever to load, but it does so some staking txn. Certainly not all of them:


https://github.com/crypto-power/cryptopower/assets/34998433/35b76b62-9b1f-40d5-8d1e-b47602d9ebac

**Comment by JoeGruffins** [comment]
trying a watching only wallet that is the default account from this wallet is showing none, but it shows alot in the info section.

**Comment by JoeGruffins** [comment]
It seems @JustinBeBoy and I came up with the same fix. I see transactions in his pr opening post. But I tried it out and it looked the same as here for me. Do you see txn in #318 @dreacot ? Do you want me to look into it more here? It may also be linked to the buggy scroll?

**Pull request closed without merging**
