### PR TITLE
multi: implement in-app network type switch

### PR DESCRIPTION
**Pull request by itswisdomagain**
- Add network type switch to settings page
- Replace --network config arg with network type settings value, default to mainnet
- Show network switch button in start page if current network has no wallets
- Implement switchToTestnetBtn click handler in DEXPage

### CODE REVIEW

**Comment by itswisdomagain** [comment]
Some screenshots

Settings page, network switch option.
Screenshot 2024-01-20 at 5 19 33 PM

Settings page, confirm network switch.
Screenshot 2024-01-20 at 5 19 46 PM

Network switch in progress
Screenshot 2024-01-20 at 5 19 49 PM

Start page after network switch, with option to switch network (only visible if current network has no wallets)
Screenshot 2024-01-20 at 5 20 32 PM

**Comment by dreacot** [comment]
trying to run the app crashes

```
% go run .                  
Config file (/Users/user/Library/Application Support/Cryptopower/cryptopower.conf) does not exist. Using defaults.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101a643e4]

goroutine 1 [running, locked to thread]:
github.com/crypto-power/cryptopower/ui/load.(*AppConfig).Values(0x10294f098?)
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/load/appconfig.go:53 +0xa4
github.com/crypto-power/cryptopower/ui/load.StartApp({0x101dc0d8f, 0x5}, {0x14000076688?, 0x100c55f8c?, 0x103733360?}, 0x14002fc9aa0, 0x14003003590)
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/load/appinfo.go:44 +0x40
main.main()
        /Users/user/go/src/github.com/crypto-power/cryptopower/main.go:101 +0x1e4
exit status 2
```

**Comment by dreacot** [comment]
trying again i get a crash while switching to testnet

```
% go run .                                                         
Config file (/Users/kennedy/Library/Application Support/Cryptopower/cryptopower.conf) does not exist. Using defaults.
2024-01-21 06:36:36.783 [INF] DLWL: Starting check and remove all dir of deleted wallets....
2024-01-21 06:36:36.784 [INF] DLWL: No wallets to clean were found
2024-01-21 06:36:36.784 [INF] DLWL: loading properties of wallet=q at location=/Users/kennedy/Library/Application Support/Cryptopower/mainnet/btc/1
2024-01-21 06:36:36.846 [INF] DLWL: loading properties of wallet=btc1 at location=/Users/kennedy/Library/Application Support/Cryptopower/mainnet/btc/2
2024-01-21 06:36:36.912 [INF] DLWL: Loaded 2 wallets
2024-01-21 06:36:39.645 [INF] BTC: Opened wallet
2024-01-21 06:36:41.485 [INF] BTC: Opened wallet
2024-01-21 06:36:41.610 [INF] BTC: Synchronizing wallet (btc1) with network...
2024-01-21 06:36:46.570 [INF] UI: Internet connection has been established
2024-01-21 06:36:51.613 [INF] BTC: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=200
2024-01-21 06:36:51.641 [INF] BTC: Seed birthday surpassed, starting recovery of wallet from height=826243 hash=000000000000000000005567ec0d1ec0643cf85fbaa27d0dd2f1f2c705a5cd00 with recovery-window=200
2024-01-21 06:36:51.770 [INF] BTC: Scanning 399 blocks for recoverable addresses
2024-01-21 06:36:57.628 [INF] BTC: Fetching block height=826571 hash=000000000000000000039e86c9bd0731c676b329f2540241e8f340d2a34acfd2
2024-01-21 06:36:59.082 [INF] BTC: Recovered addresses from blocks 826243-826641
2024-01-21 06:36:59.097 [INF] BTC: Started rescan from block 00000000000000000000e8ee3be5575195573dcaeb3ed10a5e1e80706eda19d3 (height 826641) for 1 address
2024-01-21 06:36:59.098 [ERR] BTC: Neutrino rescan ended with error: rescan exited
2024-01-21 06:36:59.100 [INF] BTC: Current sync progress update is on block 826641, target sync block is 826641
2024-01-21 06:36:59.101 [INF] BTC: Subscribing wallet (btc1) for transaction notifications
2024-01-21 06:37:12.802 [INF] DLWL: Starting check and remove all dir of deleted wallets....
2024-01-21 06:37:12.805 [INF] DLWL: No wallets to clean were found
2024-01-21 06:37:12.808 [INF] DLWL: loading properties of wallet=q at location=/Users/kennedy/Library/Application Support/Cryptopower/testnet/testnet3/btc/1
2024-01-21 06:37:12.889 [INF] DLWL: loading properties of wallet=qqq at location=/Users/kennedy/Library/Application Support/Cryptopower/testnet/testnet4/ltc/7
2024-01-21 06:37:12.940 [INF] DLWL: loading properties of wallet=dcr1 at location=/Users/kennedy/Library/Application Support/Cryptopower/testnet/testnet3/dcr/18
2024-01-21 06:37:12.955 [INF] DLWL: Loaded 3 wallets
2024-01-21 06:37:12.974 [INF] DLWL: Shutting down libwallet
2024-01-21 06:37:12.975 [INF] SHWL: (q) full network shutdown protocols completed.
2024-01-21 06:37:12.975 [INF] BTC: Canceling sync. May take a while for sync to fully cancel.
2024-01-21 06:37:12.975 [INF] BTC: (btc1) SPV wallet closed
2024-01-21 06:37:13.081 [INF] BTC: Stopping (btc1) wallet and its neutrino interface
2024-01-21 06:37:13.082 [INF] SHWL: (btc1) full network shutdown protocols completed.
2024-01-21 06:37:13.082 [INF] DLWL: db closed successfully
2024-01-21 06:37:13.082 [INF] DLWL: Shutting down log rotator
2024-01-21 06:37:13.082 [INF] DLWL: Shutdown log rotator successfully
2024-01-21 06:37:13.083 [ERR] EXT: binance: Error fetching ticker: binance failed to fetch ticker for DCRUSDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=DCRUSDT": context canceled
panic: assignment to entry in nil map

goroutine 1920 [running]:
github.com/crypto-power/cryptopower/libwallet/utils.HTTPRequest(0x14007e49ce0, {0x1043c08a0, 0x140064c1798})
        /Users/user/go/src/github.com/crypto-power/cryptopower/libwallet/utils/httpclient.go:221 +0x234
github.com/crypto-power/cryptopower/libwallet/ext.binanceGetTicker({0x103bc1b08?, 0x103bc4911?})
        /Users/user/go/src/github.com/crypto-power/cryptopower/libwallet/ext/rate_source.go:678 +0x140
github.com/crypto-power/cryptopower/libwallet/ext.(*CommonRateSource).Refresh(0x14007b906c0, 0x0)
        /Users/user/go/src/github.com/crypto-power/cryptopower/libwallet/ext/rate_source.go:521 +0x220
github.com/crypto-power/cryptopower/libwallet.(*AssetsManager).initRateSource.func1()
        /Users/user/go/src/github.com/crypto-power/cryptopower/libwallet/assets_manager.go:243 +0x50
created by github.com/crypto-power/cryptopower/libwallet.(*AssetsManager).initRateSource in goroutine 45
        /Users/user/go/src/github.com/crypto-power/cryptopower/libwallet/assets_manager.go:242 +0x2d4
exit status 2
```

**Comment by dreacot** [comment]
i switched from mainnet to testnet from the desk page and got this error going back to the dex page

Screenshot 2024-01-21 at 7 20 00 AM

**Review by dreacot — APPROVED** [review]

**Pull request merged**
