### PR TITLE
image optimization

### PR DESCRIPTION
**Pull request by JustinBeBoy**
This PR:
- Optimize the size of PNG files and replace large images
- Remove unnecessary PNG icons
- Convert some icons from using PNG to using IconVG
- Update the layout for the new icons
- Clean up some files

Result

telegram-cloud-photo-size-5-6307382916010851700-y

### CODE REVIEW

**Review by dmigwi — APPROVED** [review]
LGTM

**Review by bugjt — APPROVED** [review]

**Review by dreacot — COMMENTED** [review]
Your PR,
Screenshot from 2024-06-19 13-04-43

Master
Screenshot from 2024-06-19 13-06-40

**Comment by JustinBeBoy** [comment]
> Your PR, Screenshot from 2024-06-19 13-04-43
> 
> Master Screenshot from 2024-06-19 13-06-40

done

**Review by dreacot — APPROVED** [review]
LGTM

**Pull request merged**
